site_name: MegaBot Documentation
repo_url: https://github.com/ileonte/megabot
pages:
    - 'Introduction': 'index.md'
    - 'Building and installing': 'build.md'
    - 'Configuration': 'config.md'
    - 'Scripting': 'scripting.md'
theme: mkdocs
